### PR TITLE
example/asicwaves.rb

### PR DESCRIPTION
**Pull request by svf**
Hi. I create an example file in the fashion of your example. This file is called asicwaves.rb.

I haven't been able to test the file as I don't have my Mindwave Mobile headset with me at work, but it does work with a dummy array passed to the new method (also in the example file) called convertToBigEndianInteger.

I stole that method wholesale from a project on get hub called python-mindwave-mobile (https://github.com/robintibor/python-mindwave-mobile).

I must admit to being a bit confused as to where convertToBigEndianInteger() should live. I suspect it should live in lib/mindwave.rb, but I am unsure. Should it be a private method like the eSenseStr method?

I didn't want to just drop it into the library. By your code, you look to be a much more advanced Rubyist than I, so I thought I'd run this by you first.

Anyway, please take a look at the code at your leisure and let me know what you think if you don't mind.

I hope this finds you well.

### CODE REVIEW

**Comment by svf** [comment]
As an aside, the Mindwave Mobile creates a named device on the Mac (/dev/tty.MindWaveMobile-DevA in my case - so theoretically, your code can support more than one Bluetooth Mindwave at a time).  As long as that device is listed where you currently have your dev listed - and the Mac has previously paired with it - the Mindwave Mobile connects like a charm. I've only had it fail to connect for me once and that was due to the fact that it thought it was already connected.

**Review by whotwagner — CHANGES_REQUESTED** [review]
Hi, would you like to put line 11-26 in a seperate function and call this function in asicCall to get all the wave-values in return?  And make convertToBigEndianInteger() private. Don't forget to comment and document too.

**Comment by whotwagner** [comment]
Ah, I forgot to mention to put the code to lib/mindwave.rb

**Comment by svf** [comment]
Will do. I thought so. I was just uncertain. Thanks.

**Comment by svf** [comment]
Certainly. I'd be happy to work on that. Thanks.

**Comment by svf** [comment]
I've made the changes you have requested. At least I believe I have done it the way you wish.  Thanks.

**Review by whotwagner — APPROVED** [review]
Looks good to me. Great Job. Thank you very much.

**Comment by svf** [comment]
Thank you very much and thank you for letting me play with your project.

I am going to beat on the convertToBigEndianInteger() method and try to
compare it with the output I get from that gentleman's Python project. I'm
also going to dig through the
Neurosky docs and make sure I didn't miss anything.

Now to collect the data in a database for future processing. I might use
ActiveRecord for that.

**Comment by whotwagner** [comment]
I really appreciate that someone is working on this project. So make your changes, feel free to change the code and let's discuss the changes during the pull-requests.

Would you write a spec for convertToBigEndianInteger() in spec/mindwave_spec.rb ? It would be nice.

**Comment by svf** [comment]
It is a fun project to work on.

I've never written a spec. When you say write a spect for
convertToBigEndianInteger(), do you mean write tests for it?

I'll have to do some research.

**Pull request merged**
